site_name: QiDNA
theme:
  name: material
  features:
    - navigation.sections
    - navigation.expand
    - navigation.footer
    - navigation.path
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
nav:
  - Home: index.md
  - QiLabs: 00_QiLabs.workspace/index.md
  - QiSpark: 10_QiSpark/_index.md
  - QiServer: 20_QiServer/_index.md
  - QiMemory: 30_QiMemory/_index.md
  - QiVault: 40_QiVault/_index.md
  - QiConnect: 50_QiConnect/_index.md
  - QiApps: 60_QiApps/_index.md
  - Codex: codex.md